name: broken-link-checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 5"  # Every Friday 18:00 UTC

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq (needed for token extraction)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas bs4 openpyxl ultimate-sitemap-parser pyjwt[crypto] aiohttp

      - name: Generate JWT
        env:
          APP_ID: ${{ secrets.SECRET_APP_ID }}
          PRIVATE_KEY: ${{ secrets.SECRET_APP_KEY }}
        run: |
          JWT=$(python -c "
          import os, time, jwt
          payload = {
            'iat': int(time.time()),
            'exp': int(time.time()) + 600,
            'iss': os.environ['APP_ID']
          }
          private_key = os.environ['PRIVATE_KEY'].replace('\\\\n', '\n')
          token = jwt.encode(payload, private_key, algorithm='RS256')
          print(token)
          ")
          echo "::add-mask::$JWT"
          echo "JWT=$JWT" >> $GITHUB_ENV

      - name: Get Installation Token
        run: |
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer $JWT" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/app/installations/${{ secrets.SECRET_INSTALLATION_ID }}/access_tokens)

          INSTALLATION_TOKEN=$(echo "$RESPONSE" | jq -r '.token')

          echo "INSTALLATION_TOKEN=${INSTALLATION_TOKEN}" >> $GITHUB_ENV

      - name: Run broken link checker
        env:
          GIT_TOKEN: ${{ env.INSTALLATION_TOKEN }}
        run: |
          python broken_link_checker.py

